{% set name = "datefudge" %}
{% set version = "1.27" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: http://deb.debian.org/debian/pool/main/d/datefudge/datefudge_{{ version }}.tar.xz
  sha256: 0f7c0ca9bd2b0ef6aa01eaaf82e36b94b5424b6b70d49a8123478bf4cdfb2a2d
  patches:
    - 0001-Make-the-Makefile-portable.patch
    # https://salsa.debian.org/debian/datefudge/-/commit/508fc0f371a5b056c1b7c9379b3446eb60af774a
    - 0002-Revert-glibc-2.31-patch.patch

build:
  number: 1
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - datefudge "2003-04-01 09:42" date

about:
  home: https://packages.qa.debian.org/d/datefudge.html
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: Fake the system date

extra:
  recipe-maintainers:
    - scopatz
    - xhochy
